config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  devise_for :users
  get 'home/index'
  get '/orders' => 'orders#index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  resources :events

  root to: "home#index"

  resources :profiles do
    resources :orders
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	def self.search(search)
		where("ename LIKE ?", "%#{search}%")
	end
end

app/controllers/events_controller.rb
require 'new_event_logger'

class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin, :only => [:edit, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    if params[:search]
      @events = Event.search(params[:search]).order("created_at DESC")
    else
      @events = Event.all.order('created_at DESC')
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @order = Order.new
    @order.oname = @event.ename
    @order.odescription = @event.edescription
    @order.otime = @event.etime
    @order.ocost = @event.ecost
    @profile = Profile.find_by_user_id(current_user.id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def ensure_admin
    unless current_user && current_user.admin?
      render :text => "Access Error Message", :status => :unauthorized
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    @event.ename = params[:event][:ename]
    @event.edescription = params[:event][:edescription]
    @event.etime = params[:event][:etime]
    @event.ecost = params[:event][:ecost]

    #myEvent = BasicEvent.new(@event.ename, @event.edescription, @event.etime, @event.ecost)

    logger = NewEventLogger.instance
    logger.logInformation("New Event added: #{@event.ename}, #{@event.edescription}, #{@event.etime}, #{@event.ecost}")

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:ename, :edescription, :etime, :ecost)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :ename %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :edescription %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :etime %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :ecost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<%= form_tag events_path, :method => "get" do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search through listed events" %>
	<%= submit_tag "Search"%>
<%end%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Time</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.ename %></td>
        <td><%= event.edescription %></td>
        <td><%= event.etime %></td>
        <td><%= event.ecost %></td>
        <td><%= link_to 'Show', event %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin? %>
  <%= link_to 'New Event', new_event_path %>
<%end%>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.oname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @order.odescription %>
</p>

<p>
  <strong>Time:</strong>
  <%= @order.otime %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @order.ocost %>
</p>

<%= link_to 'New Order', new_profile_order_path(@profile, :param2 => @order.oname) %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>