config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  devise_for :users
  get 'home/index'
  get '/orders' => 'orders#index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  resources :events

  root to: "home#index"

  resources :profiles do
    resources :orders
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :profile
end

app/controllers/orders_controller.rb
require 'open_weather'
require 'new_order_logger'
require 'order_decorator'

class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @profile = Profile.find(current_user.id)

    @orders = @profile.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @profile = Profile.find_by_user_id(current_user.id)
    
    @options = { units: "metric", APPID: '58d05a1cb6c05328945b2f9f3de5ff72' }
    #City id or name can be acquirred from a database, i did not
    #have time to do this but once done this is how it would retrieve weather
    @city_id = "7778677"
    #@data = OpenWeather::Current.city("Dublin, IE", @options)
    @data = OpenWeather::Current.city_id(@city_id, @options)
    puts @data
    puts @data.keys

    @json = JSON.parse(@data.to_json)
    @temp = @json['main']['temp']
    @city = @json['name']
    @description = @json['weather'][0]['description']
  end

  # GET /orders/new
  def new
    @events = Event.all
    @profile = Profile.find(params[:profile_id])
    @order = @profile.orders.build 
    @event = Event.find_by ename: params[:param2]
    @order.oname = @event.ename
    @order.odescription = @event.edescription
    @order.otime = @event.etime
    @order.ocost = @event.ecost
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @profile = Profile.find(params[:order][:profile_id])

    @order.oname = params[:order][:oname]
    @order.odescription = params[:order][:odescription]
    @order.otime = params[:order][:otime]
    @order.ocost = params[:order][:ocost]

    myOrder = BasicOrder.new(@order.oname, @order.odescription, @order.otime, @order.ocost)

    if params[:order][:food].to_s.length > 0 then
      myOrder = FoodDecorator.new(myOrder)
    end

    if params[:order][:travel].to_s.length > 0 then
      myOrder = TravelDecorator.new(myOrder)
    end

    @order.ocost = myOrder.ocost
    @order.odescription = myOrder.details

    logger = NewOrderLogger.instance
    logger.logInformation("New Order by user #{@profile.firstname} #{@profile.lastname}: #{@order.oname}, #{@order.odescription}, #{@order.otime}, #{@order.ocost}")

    #puts "ocost from @order.ocost: #{@order.ocost}"
    #puts "odescription from @order.od: "+@order.odescription

    respond_to do |format|
      if @order.save
        format.html { redirect_to profile_order_url(@profile,@order), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy

    @profile = Profile.find(params[:profile_id])
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to profile_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:oname, :odescription, :otime, :ocost, :profile_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@profile, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :oname, :value => @order.oname, readonly: true %>
    </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_field :odescription, :value => @order.odescription, readonly: true %>
  </div>
  <div class="field">
    <%= f.label :Time %><br>
    <%= f.text_field :otime, :value => @order.otime, readonly:true %>
  </div>
  <div class="field">
    <%= f.label :Cost %><br>
    <%= f.text_field :ocost, :value => @order.ocost, readonly: true %>    
  </div>
  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id, readonly: true %>
  </div>
  <div class="field">
    Food optional: <%= check_box_tag 'order[food]', 'food' %>
  </div>
  <div class="field">
    Transport optional: <%= check_box_tag 'order[travel]', 'travel' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders for user: <%= @profile.firstname %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Time</th>
      <th>Cost</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
      <td><%= order.oname %></td>
      <td><%= order.odescription %></td>
      <td><%= order.otime %></td>
      <td><%= order.ocost %></td>
      <td><%= link_to 'Show', profile_order_path(@profile, order) %>
      <td><%= link_to 'Destroy', profile_order_path(@profile, order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </td>
      </tr>
      <%end%>
  </tbody>

</table>

<br>
<%= link_to 'Back to profile', @profile %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_orders_path(@profile) %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.oname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @order.odescription %>
</p>

<p>
  <strong>Time:</strong>
  <%= @order.otime %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @order.ocost %>
</p>

<p>
The weather for <%= @city %> is currently <%= @temp %> degrees celcius and <%= @description %>. Weather data supplied by Open Weather Map.
</p>

<%= link_to 'Back', profile_orders_path(@profile.user_id) %>